version: '3.8'

services:
   web:
    build: .
    command: python /bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/bookstore
    port:
    - 8000:8000

    depends_on:
      - db

    db:
      image: postgresql:11
      
      volumes:
        - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: